# Generated by Django 6.0.2 on 2026-02-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_eth', models.DecimalField(decimal_places=8, max_digits=18)),
                ('wallet_address', models.CharField(max_length=42)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
