# Generated by Django 6.0.2 on 2026-02-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoorder',
            name='error_message',
            field=models.TextField(blank=True, help_text='If failed, why?', null=True),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=350000.0, help_text='Rate at moment of purchase (KES/ETH)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='amount_eth',
            field=models.DecimalField(decimal_places=8, help_text='Calculated ETH to send', max_digits=18),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, help_text='Amount user pays in KES', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='checkout_request_id',
            field=models.CharField(help_text='Unique ID from Safaricom', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='mpesa_receipt',
            field=models.CharField(blank=True, help_text='The code like QFH5...', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='phone_number',
            field=models.CharField(help_text='Format: 2547XXXXXXXX', max_length=15),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for M-Pesa PIN'), ('PAID', 'M-Pesa Payment Received'), ('PROCESSING', 'Sending Crypto to Wallet'), ('COMPLETED', 'Crypto Sent Successfully'), ('FAILED', 'Transaction Failed'), ('PAID_BUT_FAILED', 'Paid but Crypto Fail')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='wallet_address',
            field=models.CharField(help_text='Ethereum public address (0x...)', max_length=42),
        ),
    ]
