# Generated by Django 6.0.2 on 2026-02-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cryptoorder_error_message_cryptoorder_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoorder',
            name='amount_eth',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='checkout_request_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='wallet_address',
            field=models.CharField(max_length=42),
        ),
    ]
