# Generated by Django 6.0.2 on 2026-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoorder',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='fee_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='request_type',
            field=models.CharField(choices=[('DEPOSIT', 'Self Deposit'), ('REQUEST', 'Payment Request from Peer')], default='DEPOSIT', max_length=10),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='requester_wallet',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='checkout_request_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for M-Pesa PIN'), ('PAID', 'M-Pesa Payment Received'), ('PROCESSING', 'Sending Crypto to Wallet'), ('COMPLETED', 'Crypto Sent Successfully'), ('FAILED', 'Transaction Failed'), ('PAID_BUT_FAILED', 'Paid but Crypto Fail')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='wallet_address',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(db_index=True, default='COMPLETED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='cryptoorder',
            index=models.Index(fields=['wallet_address', 'status'], name='payments_cr_wallet__bc4c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoorder',
            index=models.Index(fields=['requester_wallet'], name='payments_cr_request_9f5587_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoorder',
            index=models.Index(fields=['created_at'], name='payments_cr_created_8223db_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_address', 'created_at'], name='payments_tr_from_ad_4a02c6_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_address', 'created_at'], name='payments_tr_to_addr_317b4e_idx'),
        ),
    ]
